name: Build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        uses: ./.github/actions/install-pipenv 
      
      - name: Run
        run: make freeze

      - name: Commit
        uses: ./.github/actions/commit
        with:
            message: Site build
