name: Send a Tweet
on:
#   schedule:
#     - cron: "0 1,12 * * *"
  workflow_dispatch:

jobs:
  tweet:
    name: Tweet 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: 3.9

      - name: Find tweet
        id: find-tweet
        run: echo "::set-output name=tweet::$(echo `pipenv run python notebooks/tweet.py`)"
        shell: bash

      - name: Get tweet
        if: ${{steps.find-tweet.outputs.result}}
        run: echo "${{steps.find-tweet.outputs.tweet}}"

      - name: Tweet
        if: ${{steps.find-tweet.outputs.tweet}}
        uses: ethomson/send-tweet-action@v1
        with:
          status: "${{steps.find-tweet.outputs.tweet}}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

      - name: Commit
        uses: ./.github/actions/commit
        if: ${{steps.find-tweet.outputs.tweet}}
        with:
            message: Tweeted episode
