name: Send a Tweet
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        uses: ./.github/actions/install-pipenv 

      - name: Find tweet
        id: find-tweet
        run: echo "::set-output name=tweet::$(echo `make tweet`)"
        shell: bash

      - name: Get tweet
        if: ${{steps.find-tweet.outputs.result}}
        run: echo "${{steps.find-tweet.outputs.tweet}}"

#      - name: Tweet
#        uses: ethomson/send-tweet-action@v1
#        with:
#          if: ${{steps.find-tweet.outputs.result}}
#          status: "${{steps.find-tweet.outputs.result}}"
#          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
#          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
#          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
#          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

#      - name: Commit
#        uses: ./.github/actions/commit
#        with:
#            message: Tweeted episode
